replicaCount: 1

global:
  postgresql:
    auth:
      postgresPassword: "password"
      username: "lilac-user"
      password: "password123"
      database: "lilac"
    enabled: true
postgresql:
  image:
    debug: true
  primary:
    initdb:
      user: "postgres"
      password: "password"
      # scripts:
      #   init.sql: |

lilac:
  api:
    frontend:
      url:
        localhost:8080
    secret_key: mysecret
  web:
    port: 8080
    tls:
      enabled: true
      tlsSecret: 
