replicaCount: 1

global:
  postgresql:
    auth:
      postgresPassword: "password"
      username: "lilac-user"
      password: "password123"
      database: "lilac"
    enabled: true
postgresql:
  image:
    debug: true
  primary:
    initdb:
      user: "postgres"
      password: "password"
      scripts:
        init.sql: |
          CREATE USER "lilac-mlflow" WITH ENCRYPTED PASSWORD 'password123';
          CREATE DATABASE "lilac-mlflow-auth";
          GRANT ALL PRIVILEGES ON DATABASE "lilac-mlflow-auth" TO "lilac-mlflow";
          ALTER DATABASE "lilac-mlflow-auth" OWNER TO "lilac-mlflow";
          CREATE DATABASE "lilac-mlflow";
          GRANT ALL PRIVILEGES ON DATABASE "lilac-mlflow" TO "lilac-mlflow";
          ALTER DATABASE "lilac-mlflow" OWNER TO "lilac-mlflow";
cilium:
  hubble:
    ui:
      enabled: true
    relay:
      enabled: true

lilac:
  api:
    frontend:
      url:
        localhost:8080
    secret_key: mysecret

  web:
    port: 8080
    tls:
      enabled: true
      tlsSecret: 
