replicaCount: 1

global:
  postgresql:
    auth:
      postgresPassword: "password"
      username: "lilac-user"
      password: "password123"
      database: "lilac"
    enabled: true
cilium:
  hubble:
    ui:
      enabled: true
    relay:
      enabled: true

google:
  clientId: <GOOGLE_CLIENT_ID>
  clientSecret: <GOOGLE_CLIENT_SECRET>
  issuerUrl: https://accounts.google.com
oauth:
  redirectUri: http://localhost:8080/auth/callback
frontend:
  url: http://localhost:8080
github:
  authUrl: https://github.com/login/oauth/authorize
  tokenUrl: https://github.com/login/oauth/access_token
  clientId: <GITHUB_CLIENT_ID>
  clientSecret: <GITHUB_CLIENT_SECRET>
  userInfoUrl: https://api.github.com/user
