replicaCount: 1

global:
  postgresql:
    auth:
      postgresPassword: "password"
      username: "lilac-user"
      password: "password123"
      database: "lilac"
    enabled: true
postgresql:
  image:
    debug: true
  primary:
    initdb:
      user: "postgres"
      password: "password"
      scripts:
        init.sql: |
          CREATE USER "lilac-mlflow" WITH ENCRYPTED PASSWORD 'password123';
          CREATE DATABASE "lilac-mlflow-auth";
          GRANT ALL PRIVILEGES ON DATABASE "lilac-mlflow-auth" TO "lilac-mlflow";
          ALTER DATABASE "lilac-mlflow-auth" OWNER TO "lilac-mlflow";
          CREATE DATABASE "lilac-mlflow";
          GRANT ALL PRIVILEGES ON DATABASE "lilac-mlflow" TO "lilac-mlflow";
          ALTER DATABASE "lilac-mlflow" OWNER TO "lilac-mlflow";
cilium:
  hubble:
    ui:
      enabled: true
    relay:
      enabled: true

google:
  clientId: <GOOGLE_CLIENT_ID>
  clientSecret: <GOOGLE_CLIENT_SECRET>
  issuerUrl: https://accounts.google.com
oauth:
  redirectUri: http://localhost:8080/auth/callback
frontend:
  url: http://localhost:8080
github:
  authUrl: https://github.com/login/oauth/authorize
  tokenUrl: https://github.com/login/oauth/access_token
  clientId: <GITHUB_CLIENT_ID>
  clientSecret: <GITHUB_CLIENT_SECRET>
  userInfoUrl: https://api.github.com/user

mlflow:
  tracking:
    auth:
      password: "password12345"
  postgresql:
    enabled: false
  externalDatabase:
    host: lilac-postgresql
    port: 5432
    user: "lilac-mlflow"
    password: "password123"
    database: "lilac-mlflow"
    authDatabase: "lilac-mlflow-auth"
  ingress:
    enabled: false
  service:
    type: ClusterIP
    port: 5000
