[workspace]
resolver = "2"
members = [ "controlplane-api","data-pipeline"]


[workspace.dependencies]
argon2 = "0.5"
aws-lc-rs = "1"
axum = "0.8"
http-body-util = "0.1"
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
password-auth = "1.0.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
