apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "lilac-web-network-policy"
spec:
  endpointSelector:
    matchLabels:
      id: lilac-web
  ingress:
  - fromCIDR:
    - "0.0.0.0/0"
    toPorts:
    - ports:
      - port: "8080"
        protocol: TCP