services:
  controlplane:
    build:
      context: ../
      dockerfile: ./docker/controlplane/Dockerfile.alpine
    command: /usr/local/app/controlplane-api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../.env
    environment:
      - DATABASE_URL=postgres://postgres:password@db/database
    ports:
      - '3000:3000'
    volumes:
      - ../backend/data-pipeline:/usr/local/app/data-pipeline:rw
    networks:
      - default

  db:
    image: postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: {}

networks:
  network: {}